services:
  dev-finder-db:
    image: postgres
    restart: always
    container_name: dev-finder-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: riyadh
      POSTGRES_PASSWORD: 1209
      POSTGRES_DB: dev_finder
    volumes:
      - ./postgres:/var/lib/postgresql/data
